# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS via apt
      run: sudo apt install nodejs     
    - name: Install NPM via apt
      run: sudo apt install npm
    - name: NPM Version
      run: npm --version
    - name: NPM Rebuild
      run: npm rebuild
    - name: Install marcjs via Node
      run: npm install marcjs
    - name: Run NPM Test
      run: node mrc2scsb.js --marc "test/test_multiple_callnumbers.mrc" --barcode "test/barcode.test.txt" --dupecheck "test/temp_dupecheck.txt"
    # - name: Install marcjs via Node
    #   run: |
    #     npm i marcjs
    # - name: Install @mapbox/node-pre-gyp via Node
    #   run: |
    #     npm uninstall node-pre-gyp --save
    #     npm install @mapbox/node-pre-gyp --save
    # - name: NPM Install
    #   run: npm install
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: 5.0.0
    # - name: Install Mocha via apt command
    #   run: sudo apt install mocha
    # - name: Install @mapbox/node-pre-gyp via Node
    #   run: |
    #     npm uninstall node-pre-gyp --save
    #     npm install @mapbox/node-pre-gyp
    # - name: Install node-pre-gyp via Node
    #   run: |
    #     npm uninstall node-pre-gyp --save
    #     npm i @mapbox/node-pre-gyp --save
    # - name: Install Babel Dependencies
    #  run: |
    #     npm install --save-dev @babel/polyfill
    #     npm install --save-dev @babel/register
    # - name: Look at folder structure
    #   run: |
    #     ls
    # - name: Run Mocha tests
    #   run: |
    #     mocha --require @babel/register --require @babel/polyfill mrc2scsb.js
        
